- name: "update rollout strategy"
  command: oc patch config.imageregistry.operator.openshift.io/cluster --type=merge --patch '{"spec":{"rolloutStrategy":"Recreate","replicas":1}}'

- name: Show current yaml for rolloutStrategy
  command: oc describe config.imageregistry.operator.openshift.io/cluster

- name: Create install-dir
  file: 
    path: "{{ playbook_dir }}/{{ item }}"
    state: directory
    mode: '0755'
  with_items: ["install-dir"]

- name: Copy pvc file to install-dir
  template:
    src: "{{ playbook_dir }}/roles/block_reg/templates/reg-pvc.yaml.j2"
    dest: "{{ playbook_dir }}/install-dir/reg-pvc.yaml"

- name: create pvc for reg storage
  command: oc create -f install-dir/reg-pvc.yaml -n openshift-image-registry
  ignore_errors: True

- name: edit reg operator config for pvc
  command: oc patch config.imageregistry.operator.openshift.io/cluster --type=merge --patch '{"spec":{"storage":{"pvc":{"claim":"image-registry-storage"}}}}'
  ignore_errors: True

- name: Set registry to managed
  command: oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"managementState":"Managed"}}'
  ignore_errors: True